### ISSUE TITLE
Chapter 5: Unhandled Rejection (Error): This contract object doesn't have address set yet, please set an address first.

### ISSUE THREAD

**Issue by isseium** [RedSquirrelTech/hoscdev#38]
Hi, 

I got error on Chapter 5.

I executed `npm run start` after `truffle migrate --network development`.
and access to http://localhost:3000

![image](https://user-images.githubusercontent.com/291176/106272289-2ae04000-6274-11eb-9f44-29ade492cc58.png)

How to set an address?

**Comment by isseium** [comment]
I resolved this issue.

I had connected via Mainnet on MetaMask.
It is working after switch Goerli Test Network.

![image](https://user-images.githubusercontent.com/291176/106273434-02f1dc00-6276-11eb-95cb-a8fb63228bae.png)

Thank you.

**Comment by isseium** [comment]
FYI:

On Goerli Test Network, I could not execute submit because I have no gas.
So I added custom network on MetaMask. I could execute submit.

![image](https://user-images.githubusercontent.com/291176/106274277-5c0e3f80-6277-11eb-8267-50eba1caebd7.png)

**Comment by SatoshiKawabata** [comment]
I got this message. I can't add a new network. What does this message mean?
![image](https://user-images.githubusercontent.com/1194571/147940486-23d428b9-3299-49eb-93e4-423b328d277d.png)

**Comment by rai62** [comment]
This problem can be resolved just by switching "Localhost 8545" network.

<img width="341" alt="Screen Shot 2022-02-09 at 14 08 51" src="https://user-images.githubusercontent.com/83504221/153126647-995fc2be-b225-4a4f-86bc-c9bdc1cae468.png">

In addition, we can use accounts who have 100 ETH because Ganache has the 10 accounts as default.
Use PRIVATE KEY by pressing "Show Keys" at the right edge of the screen in account tab.

<img width="350" alt="Screen Shot 2022-02-09 at 14 27 07" src="https://user-images.githubusercontent.com/83504221/153127610-2a9d5b25-504f-40c9-904a-5bca03fdffc4.png">

Then, we can add the accounts to MetaMask and send them ETH each other!

**Comment by atulkadyan** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/121191268/213357571-0b1f2bb0-f5bd-41e2-b7d5-54397a758775.png">
Hi i am getting this error please help me asap, I have connected using ganache cli and still gets this message.
